### PR TITLE
Fixes deprecated Mod Menu metadata API usage.

### LINKED ISSUE #42: Using Deprecated Mod Menu API
`[12:54:45] [main/WARN] (Mod Menu) WARNING! Mod fabric-language-kotlin is only using deprecated 'modmenu:api' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.`

Not sure if you guys are aware of this but I thought I would just notify you about this here!

### PR DESCRIPTION
**Pull request by NinjaPhenix**
Fixes https://github.com/FabricMC/fabric-language-kotlin/issues/42.

### CODE REVIEW

**Comment by modmuss50** [comment]
This should have never been added here in the first place.

**Comment by NinjaPhenix** [comment]
So just remove the modmenu custom key?

**Comment by modmuss50** [comment]
Yes please.

**Review by modmuss50 — APPROVED** [review]

**Comment by modmuss50** [comment]
Ill merge this in for inclusion in the next release, clearly doesnt need a release on of its own.

Thanks 👍

**Pull request merged**
