### PR TITLE
Add ModMenu icon

### PR DESCRIPTION
**Pull request by sargunv**
I added an icon for ModMenu. I got the icon from JetBrains's [official press materials](https://www.jetbrains.com/company/press/), and made sure to follow their guidelines for usage of their logos (specifically min size 50px with > 10% padding around it, on a black background).

Here's what it looks like in game:

### CODE REVIEW

**Comment by asiekierka** [comment]
Hold this PR until Loader 0.4.0 comes as it introduces a standard for icons.

**Comment by sargunv** [comment]
Sure

**Comment by NikkyAI** [comment]
implemented in #6 
ModMenu supports the 0.4.0 `icon` key and soon more of the `author` and `contact` too i hope

**Comment by sargunv** [comment]
Cool, I'll close this then

**Pull request closed without merging**
