### PR TITLE
Refactor readme

### PR DESCRIPTION
**Pull request by jakobkmar**
- created a table for all entrypoint samples to improve the readability
- updated documentation links, removed dead links
- added modrinth shield

### CODE REVIEW

**Comment by jakobkmar** [comment]
Here you can find the [rendered readme](https://github.com/jakobkmar/fabric-language-kotlin/blob/refactor_readme/README.md).

**Review by modmuss50 — APPROVED** [review]
Looks great 👍

**Comment by jakobkmar** [comment]
In case you missed it, PR is not a draft anymore :)

**Comment by modmuss50** [comment]
I did, thanks :)

**Pull request merged**
